### ISSUE TITLE
MousePassThrough option for windows version

### ISSUE THREAD

**Issue by im-izz** [crgimenes/neko#37] opened 2024-09-28 15:01 UTC
-mousepassthrough parameter doesn't work in windows

**Comment by crgimenes** [comment] 2024-09-29 06:19
Unfortunately, I don't have Windows machines to test the problem.

**Comment by im-izz** [comment] 2024-09-29 11:10
This is what I get tho, Might that be helpful

![image](https://github.com/user-attachments/assets/53a1e39c-e0dc-4623-99f5-d35331a12ab5)

**Comment by arrlancore** [comment] 2024-09-30 04:45
hi @crgimenes I have a Windows machine set up for testing, I'd be happy to help fix this. can you assign to me?

**Comment by crgimenes** [comment] 2024-09-30 12:08
> hi @crgimenes I have a Windows machine set up for testing, I'd be happy to help fix this. can you assign to me?

Thanks for the help! I believe the problem is with Ebitengine, but I'm not sure, I didn't find any issues about it.

**Comment by arrlancore** [comment] 2024-10-01 02:59
yes correct, there no issue in my windows machine with latest version go.
![image](https://github.com/user-attachments/assets/f87e7fb9-621a-4f90-82ce-c70e24ca85b8)

**Closed** 2024-10-01 03:02 UTC
Labels: bug, help wanted

**Comment by im-izz** [comment] 2024-10-01 03:06
Yay :D, so where to update or get the binary?
